pub struct Token {
    token_type: TokenType,
    value: String,
}

pub enum TokenType {
    L_PARENS = "L_PARENS",
    R_PARENS = "R_PARENS",
    L_BRACE = "L_BRACE",
    R_BRACE = "R_BRACE",
    L_SBRACKET = "L_BRACKET",
    R_BRACKET = "R_BRACKET",

    // comparison operators
    EQUAL_OPERATOR = "EQUAL_OPERATOR",
    NOT_EQUAL_OPERATOR = "NOT_EQUAL_OPERATOR",
    GREATER_THAN_OPERATOR = "GREATER_THAN_OPERATOR",
    LESS_THAN_OPERATOR = "LESS_THAN_OPERATOR",
    GREATER_THAN_EQUAL_OPERATOR = "GREATER_THAN_EQUAL_OPERATOR",
    LESS_THAN_EQUAL_OPERATOR = "LESS_THAN_EQUAL_OPERATOR",

    // logical operators
    AND_OPERATOR = "AND_OPERATOR",
    OR_OPERATOR = "OR_OPERATOR",
    NOT_OPERATOR = "NOT_OPERATOR",

    // assignment operators
    INITIALIZE_OPERATOR = "INITIALIZE_OPERATOR",
    ASSIGNMENT_OPERATOR = "ASSIGNMENT_OPERATOR",
    PLUS_EQUALS = "PLUS_EQUALS",
    MINUS_EQUALS = "MINUS_EQUALS",

    // math operators
    ADDITION_OPERATOR = "ADDITION_OPERATOR",
    SUBTRACTION_OPERATOR = "SUBTRACTION_OPERATOR",
    MULTIPLICATION_OPERATOR = "MULTIPLICATION_OPERATOR",
    DIVISION_OPERATOR = "DIVISION_OPERATOR",
    MODULUS_OPERATOR = "MODULUS_OPERATOR",

    // conditionals
    IF = "IF",
    ELSE = "ELSE",

    // loops
    FOR_LOOP = "FOR_LOOP",
    WHILE_LOOP = "WHILE_LOOP",

    FUNCTION = "FUNCTION",
    RETURN = "RETURN",

}
